name = "JuLOOa"
uuid = "d560117c-e80f-4758-b510-1cb1d9ee831f"
authors = ["Carlos Parada <paradac@carleton.edu>"]
version = "0.0.0"

[deps]
PkgTemplates = "14b8a8f1-9102-5b29-a752-f990bacb7fe1"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
