name = "JuLOOa"
uuid = "d560117c-e80f-4758-b510-1cb1d9ee831f"
authors = ["Carlos Parada <paradac@carleton.edu>"]
version = "0.0.2"

[deps]
VectorizationBase = "3d5dd08c-fd9d-11e8-17fa-ed2836048c2f"

[compat]
VectorizationBase = "0.20"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
